// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx0-xIF7yjdo31SolkC8BXZ35GQLLKbqA',
    appId: '1:783159057095:web:37dffe34b6778a43243ce2',
    messagingSenderId: '783159057095',
    projectId: 'taskroom-50849',
    authDomain: 'taskroom-50849.firebaseapp.com',
    storageBucket: 'taskroom-50849.firebasestorage.app',
    measurementId: 'G-S02BW7WNWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADab1wa0XBjaxGGpwDcYOfHp_Gtl8gu4s',
    appId: '1:783159057095:android:433a7e67f4d146b7243ce2',
    messagingSenderId: '783159057095',
    projectId: 'taskroom-50849',
    storageBucket: 'taskroom-50849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfrKYbYAavgYqmmP8Uqfry8Mxy0uW_Fs',
    appId: '1:783159057095:ios:7f2db58beaa3b355243ce2',
    messagingSenderId: '783159057095',
    projectId: 'taskroom-50849',
    storageBucket: 'taskroom-50849.firebasestorage.app',
    iosBundleId: 'com.taskroom.app',
  );

}