// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41pz710rM5GGLoBX4W_vifM15UqyAlBY',
    appId: '1:183578397733:web:4597876ac499486a3cc3cc',
    messagingSenderId: '183578397733',
    projectId: 'taskroom-app-ecf05',
    authDomain: 'taskroom-app-ecf05.firebaseapp.com',
    storageBucket: 'taskroom-app-ecf05.firebasestorage.app',
    measurementId: 'G-SQJWK1KYBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD85QZV28y00fOOIuQnbgTblu5XBHbQh8',
    appId: '1:183578397733:android:3b35d6f76c0729323cc3cc',
    messagingSenderId: '183578397733',
    projectId: 'taskroom-app-ecf05',
    storageBucket: 'taskroom-app-ecf05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnwSc9BSxJiB0-MiDx5GtJ6VBYDvx7M4o',
    appId: '1:183578397733:ios:487e4d31fc408bbd3cc3cc',
    messagingSenderId: '183578397733',
    projectId: 'taskroom-app-ecf05',
    storageBucket: 'taskroom-app-ecf05.firebasestorage.app',
    iosBundleId: 'com.example.fieldWork',
  );
}
